import os
import json

# Setup directories
with open("config.json", "r") as f:
  config = json.load(f)
DATADIR = config["datadir"]
os.makedirs(DATADIR, exist_ok=True)
os.makedirs(os.path.join(DATADIR,"sim_data"), exist_ok=True)
RESULTSDIR = config["resultsdir"]
os.makedirs(RESULTSDIR, exist_ok=True)
IMGDIR = config["imgdir"]
os.makedirs(IMGDIR, exist_ok=True)
os.makedirs('job_reports', exist_ok=True)

rule all:
  input:
    "docs/simulations.html",
    "docs/umvcue.html",
    "docs/replication_report.html"

SIMS=list(range(1,12))
chunk_size=20000
# Create simulated data
rule sim_data:
  output:
    "{DATADIR}/sim_data/out{SIMS}.rdata"
  shell:
    "Rscript scripts/sim_overlap.r {chunk_size} {wildcards.SIMS} {DATADIR}"

# Aggregate the results
rule aggregate:
  input:
    expand("{DATADIR}/sim_data/out{SIMS}.rdata", DATADIR = DATADIR, SIMS = SIMS)
  output:
    "{DATADIR}/sim_overlap_nr.rdata"
  shell:
    "Rscript scripts/sim_aggregate.r {DATADIR}"


# Do the replication simulations
rule umvcue:
  input:
    "docs/umvcue.rmd"
  output:
    "docs/umvcue.html"
  shell:
    "cd docs; Rscript -e \"rmarkdown::render('umvcue.rmd', output_format='all')\""

rule replication:
  output:
    expand("{RESULTSDIR}/replication.rdata", RESULTSDIR=RESULTSDIR),
  shell:
    "Rscript scripts/replication.r {RESULTSDIR}"

rule replication_report:
  input:
    "docs/replication_report.rmd",
    expand("{RESULTSDIR}/replication.rdata", RESULTSDIR=RESULTSDIR)
  output:
    expand("{IMGDIR}/replication_beta_0.png", IMGDIR=IMGDIR),
    expand("{IMGDIR}/replication_prop_sig_0.png", IMGDIR=IMGDIR),
    expand("{IMGDIR}/replication_beta_0.2.png", IMGDIR=IMGDIR),
    expand("{IMGDIR}/replication_prop_sig_0.2.png", IMGDIR=IMGDIR),
    "docs/replication_report.html"
  shell:
    "cd docs; Rscript -e \"rmarkdown::render('replication_report.rmd', output_format='all')\" {IMGDIR} {RESULTSDIR}"


# Collapse all the results into one file
rule collapse:
  input:
    "docs/simulations.rmd",
    expand("{DATADIR}/sim_overlap_nr.rdata", DATADIR = DATADIR),
    expand("{IMGDIR}/replication_beta_0.png", IMGDIR = IMGDIR),
    expand("{IMGDIR}/replication_prop_sig_0.png", IMGDIR = IMGDIR),
    expand("{IMGDIR}/replication_beta_0.2.png", IMGDIR = IMGDIR),
    expand("{IMGDIR}/replication_prop_sig_0.2.png", IMGDIR = IMGDIR)
  output:
    "docs/simulations.html"
  shell:
    "cd docs; Rscript -e \"rmarkdown::render('simulations.rmd', output_format='all')\" {DATADIR}"
