---
title: "Analysis of replication simulations"
output:
  html_document:
    df_print: paged
---

```{r}
suppressWarnings(suppressPackageStartupMessages({
  library(simulateGP)
  library(TwoSampleMR)
  library(dplyr)
  library(ggplot2)
  library(parallel)
  library(knitr)
  library(pROC)
}))
args <- commandArgs(T)
imgdir <- args[1]
datadir <- args[2]
opts_chunk$set(cache=TRUE, echo=TRUE, message=FALSE, warning=FALSE)
load(file.path("../results/replication.rdata"))
```


Create figure

```{r}
ress <- filter(res) %>%
  tidyr::separate(what, into=c("exposure_dataset", "instruments"), "_") %>%
  group_by(exposure_dataset, instruments, overlap, buy, bxy) %>%
  summarise( n=n(), z=mean(abs(b/se)),prop_sig = sum(pnorm(abs(b/se), lower.tail=FALSE) < 0.05) / n(), se=sd(b)/sqrt(n),b=mean(b))
```


```{r}
# Plot beta
p1 <- ggplot(subset(ress, bxy==0), aes(x=overlap, y=b, fill=exposure_dataset)) +
geom_bar(stat="identity", position="dodge", aes(fill=exposure_dataset)) +
geom_errorbar(aes(ymin = b - se, ymax = b + se), width=0.1,position=position_dodge(0.9)) +
facet_grid(instruments ~ buy) +
scale_fill_brewer(type="qual") +
geom_hline(yintercept=0, linetype="dotted") +
theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
p1
```

```{r}
p1 <- ggplot(subset(ress, bxy==0.2), aes(x=overlap, y=b, fill=exposure_dataset)) +
geom_bar(stat="identity", position="dodge", aes(fill=exposure_dataset)) +
geom_errorbar(aes(ymin = b - se, ymax = b + se), width=0.1,position=position_dodge(0.9)) +
facet_grid(instruments ~ buy) +
scale_fill_brewer(type="qual") +
geom_hline(yintercept=0.2, linetype="dotted") +
theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
p1
```


# Plot proportion of significant p vals

```{r}
p1 <- ggplot(subset(ress, bxy==0), aes(x=overlap, y=prop_sig, fill=exposure_dataset)) +
geom_bar(stat="identity", position="dodge", aes(fill=exposure_dataset)) +
facet_grid(instruments ~ buy) +
scale_fill_brewer(type="qual") +
theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
p1
```

```{r}
p1 <- ggplot(subset(ress, bxy==0.2), aes(x=overlap, y=prop_sig, fill=exposure_dataset)) +
geom_bar(stat="identity", position="dodge", aes(fill=exposure_dataset)) +
facet_grid(instruments ~ buy) +
scale_fill_brewer(type="qual") +
theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
p1
```

## AUROC

```{r}
# Remove the next line after changes in replication.r!!!!!!!!!!!!! rep_meta -> meta_sig
#res$what <- gsub('rep_meta', 'meta_sig', res$what)

ress2 <- filter(res) %>%
  tidyr::separate(what, into=c("exposure_dataset", "instruments"), "_") %>%
  group_by(exposure_dataset, instruments, overlap, buy) %>%
  summarise(
    auroc = roc(bxy, pval)$auc %>% as.numeric(),
    fdr = sum(pval < 0.05 & bxy == 0, na.rm=TRUE) / sum(bxy == 0, na.rm=TRUE),
    power = sum(pval < 0.05 & bxy != 0, na.rm=TRUE) / sum(bxy != 0, na.rm=TRUE)
  )

ggplot(ress2 %>% subset(instruments == "sig"), aes(x=fdr, y=power)) +
geom_point(aes(colour=overlap, shape=exposure_dataset)) +
facet_grid(. ~ buy) +
scale_colour_brewer(type="qual") +
labs(x="False discovery rate (α=0.05)", y="Power (p < 0.05)", shape="Exposure dataset", colour="Outcome dataset")
```

