---
title: UMVCUE and winner's curse
---

```{r}
suppressWarnings(suppressPackageStartupMessages({
  library(simulateGP)
  library(TwoSampleMR)
  library(dplyr)
  library(ggplot2)
  library(parallel)
  library(knitr)
  library(tidyverse)
  args <- commandArgs(T)
  datadir <- args[1]
}))
opts_chunk$set(cache=TRUE, echo=TRUE, message=FALSE, warning=FALSE)
```


### Find GWAS parameters which will likely give high winner's curse


```{r}
simulate_gwasx <- function(nid, nsnp, bgx, bux)
{
  g <- make_geno(nid, nsnp, 0.5)
  u <- rnorm(nid)
  geneff <- rep(bgx, nsnp)
  x <- make_phen(c(geneff, bux), cbind(g, u))
  gwas(x, g)
}
sapply(1:1000, function(x)
{
  simulate_gwasx(3000, 20, 0.08, 0.4) %>%
    {sum(.$pval < 5e-8)}
}) %>% table
```


### Check that UMVCUE works at reducing winner's curse

```{r}
umvcue <- function(d_beta, r_beta, d_se, r_se, pthresh)
{
  t <- qnorm(1 - pthresh/2)
  MLE <- (r_se^2 * d_beta + d_se^2 * r_beta) / (r_se^2 + d_se^2)
  BB <- (sqrt(r_se^2 + d_se^2) / d_se^2) * (MLE - t * d_se)
  b <- MLE - (r_se^2 / sqrt(r_se^2 + d_se^2) * dnorm(BB) / pnorm(BB))
  return(b)
}
simulate_umvcue <- function(nid, nsnp, bgx, bux)
{
  geneff <- rep(bgx, nsnp)
  g <- make_geno(nid/2, nsnp, 0.5)
  u <- rnorm(nid/2)
  x <- make_phen(c(geneff, bux), cbind(g, u))
  d <- gwas(x, g)
  g <- make_geno(nid/2, nsnp, 0.5)
  u <- rnorm(nid/2)
  x <- make_phen(c(geneff, bux), cbind(g, u))
  r <- gwas(x, g)
  index <- d$pval < 5e-8
  dat <- tibble(
    truth = geneff,
    disc = d$bhat,
    rep = r$bhat,
    disc_sig = d$pval < 5e-8,
    what="all"
  )
  dat$umvcue <- NA
  if(any(index))
  {
    dat$umvcue[index] <- umvcue(d$bhat[index], r$bhat[index], d$se[index], r$se[index], 5e-8)
  }
  return(dat)
}
out <- lapply(1:1000, function(x)
{
  simulate_umvcue(3000, 20, 0.13, 0.4) %>%
    mutate(sim=x)
}) %>% bind_rows()
out2 <- group_by(out, sim) %>%
  summarise(
    nsig=sum(disc_sig), 
    truth=mean(truth),
    disc = mean(disc),
    rep = mean(rep),
    umvcue = mean(umvcue, na.rm=T)
  )
out3 <- filter(out, disc_sig) %>%
  group_by(sim) %>%
  summarise(
    nsig=sum(disc_sig), 
    truth=mean(truth),
    disc = mean(disc),
    rep = mean(rep),
    umvcue = mean(umvcue, na.rm=T)
  )
colMeans(out2)
colMeans(out3)
```

it does reduce winner's curse, gives simular result to replication

