import os
import json

# Setup directories
with open("config.json", "r") as f:
  config = json.load(f)
DATADIR = config["datadir"]
os.makedirs(DATADIR, exist_ok=True)
os.makedirs(os.path.join(DATADIR,"sim_data"), exist_ok=True)
RESULTSDIR = config["resultsdir"]
os.makedirs(RESULTSDIR, exist_ok=True)
IMGDIR = config["imgdir"]
os.makedirs(IMGDIR, exist_ok=True)
os.makedirs('job_reports', exist_ok=True)

rule all:
  input:
    expand("./simulations.html")

SIMS=list(range(1,1213))
chunk_size=20000
# Create simulated data
rule sim_data:
  output:
    "{DATADIR}/sim_data/out{SIMS}.rdata"
  shell:
    "Rscript sim_overlap.r {chunk_size} {wildcards.SIMS} {DATADIR}"

# Aggregate the results
rule aggregate:
  input:
    expand("{DATADIR}/sim_data/out{SIMS}.rdata", DATADIR = DATADIR, SIMS = SIMS)
  output:
    "{DATADIR}/sim_overlap_nr.rdata"
  shell:
    "Rscript sim_aggregate.r {DATADIR}"

# Do the replication simulations
rule replication:
  output:
    "{IMGDIR}/replication_beta_0.png",
    "{IMGDIR}/replication_prop_sig_0.png",
    "{IMGDIR}/replication_beta_0.2.png",
    "{IMGDIR}/replication_prop_sig_0.2.png"
  shell:
    "Rscript -e \"rmarkdown::render('replication.rmd', output_format='all')\" {IMGDIR}"

# Collapse all the results into one file
rule collapse:
  input:
    expand("{DATADIR}/sim_overlap_nr.rdata", DATADIR = DATADIR),
    expand("{IMGDIR}/replication_beta_0.png", IMGDIR = IMGDIR),
    expand("{IMGDIR}/replication_prop_sig_0.png", IMGDIR = IMGDIR),
    expand("{IMGDIR}/replication_beta_0.2.png", IMGDIR = IMGDIR),
    expand("{IMGDIR}/replication_prop_sig_0.2.png", IMGDIR = IMGDIR)
  output:
    "./simulations.html"
  shell:
    "Rscript -e \"rmarkdown::render('simulations.rmd', output_format='all')\" {DATADIR}"


